package com.coinlive.chat.api.model.enums

import androidx.annotation.Keep

@Keep
enum class ResponseCode {
    SUCCESS,
    FAIL,
    REGISTERED_NICKNAME,
    REGISTERED_MEMBER,
    INVALID_NICKNAME_FORMAT,
    INVALID_NICKNAME,
    INVALID_TOKEN,
    INVALID_KEY,
    INVALID_STATUS,
    EXCEEDING_CERTIFICATIONS,
    UNKNOWN_MEMBER,
    DUPLICATED,
    PARAMETER_ERROR,
    TIMEOUT,
    PERMISSION_DENIED,
    NOT_SUPPORTED,
    NOT_FOUND,
    SERVER_ERROR,
    ALREADY_REGISTERED,
    UPLOAD_FAILED,
    PROFILE_UPLOAD
}